//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerCloud.Assignment1.UnitTests.ProductServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductDTO", Namespace="http://schemas.datacontract.org/2004/07/CustomerCloud.DTOs")]
    [System.SerializableAttribute()]
    public partial class ProductDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductServiceReference.IProduct")]
    public interface IProduct {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/Create", ReplyAction="http://tempuri.org/IProduct/CreateResponse")]
        void Create(CustomerCloud.Assignment1.UnitTests.ProductServiceReference.ProductDTO product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/Create", ReplyAction="http://tempuri.org/IProduct/CreateResponse")]
        System.Threading.Tasks.Task CreateAsync(CustomerCloud.Assignment1.UnitTests.ProductServiceReference.ProductDTO product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/Delete", ReplyAction="http://tempuri.org/IProduct/DeleteResponse")]
        void Delete(System.Guid Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/Delete", ReplyAction="http://tempuri.org/IProduct/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(System.Guid Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/Read", ReplyAction="http://tempuri.org/IProduct/ReadResponse")]
        CustomerCloud.Assignment1.UnitTests.ProductServiceReference.ProductDTO Read(System.Guid Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/Read", ReplyAction="http://tempuri.org/IProduct/ReadResponse")]
        System.Threading.Tasks.Task<CustomerCloud.Assignment1.UnitTests.ProductServiceReference.ProductDTO> ReadAsync(System.Guid Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/Update", ReplyAction="http://tempuri.org/IProduct/UpdateResponse")]
        void Update(CustomerCloud.Assignment1.UnitTests.ProductServiceReference.ProductDTO product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/Update", ReplyAction="http://tempuri.org/IProduct/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(CustomerCloud.Assignment1.UnitTests.ProductServiceReference.ProductDTO product);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductChannel : CustomerCloud.Assignment1.UnitTests.ProductServiceReference.IProduct, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductClient : System.ServiceModel.ClientBase<CustomerCloud.Assignment1.UnitTests.ProductServiceReference.IProduct>, CustomerCloud.Assignment1.UnitTests.ProductServiceReference.IProduct {
        
        public ProductClient() {
        }
        
        public ProductClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Create(CustomerCloud.Assignment1.UnitTests.ProductServiceReference.ProductDTO product) {
            base.Channel.Create(product);
        }
        
        public System.Threading.Tasks.Task CreateAsync(CustomerCloud.Assignment1.UnitTests.ProductServiceReference.ProductDTO product) {
            return base.Channel.CreateAsync(product);
        }
        
        public void Delete(System.Guid Id) {
            base.Channel.Delete(Id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(System.Guid Id) {
            return base.Channel.DeleteAsync(Id);
        }
        
        public CustomerCloud.Assignment1.UnitTests.ProductServiceReference.ProductDTO Read(System.Guid Id) {
            return base.Channel.Read(Id);
        }
        
        public System.Threading.Tasks.Task<CustomerCloud.Assignment1.UnitTests.ProductServiceReference.ProductDTO> ReadAsync(System.Guid Id) {
            return base.Channel.ReadAsync(Id);
        }
        
        public void Update(CustomerCloud.Assignment1.UnitTests.ProductServiceReference.ProductDTO product) {
            base.Channel.Update(product);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(CustomerCloud.Assignment1.UnitTests.ProductServiceReference.ProductDTO product) {
            return base.Channel.UpdateAsync(product);
        }
    }
}
